# Use the official Node.js image as a base
FROM node:16

# Set working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port the app runs on
EXPOSE 8015

# Command to run the server
CMD ["node", "server.js"]
